### ISSUE TITLE
aws redshift not created

### ISSUE THREAD

**Issue by shivnarayanan** [josephmachado/beginner_de_project#14] opened 2022-03-08 04:47 UTC
<img width="567" alt="image" src="https://user-images.githubusercontent.com/48608506/157168000-0541c9f2-bcfc-4c60-a4b4-855dda05aad8.png">

**Comment by josephmachado** [comment] 2022-03-08 13:22
@shivnarayanan It looks like redshift cluster is created, but the problem is with Airflow webserver docker container. Can you

1. Check if Redshift cluster is created in AWS UI?
2. Check if the webserver and scheduler containers are running using `docker ls`
3. Make sure your docker setting has at least 4GB memory.

LMK

**Comment by shivnarayanan** [comment] 2022-03-08 13:42
<img width="1375" alt="image" src="https://user-images.githubusercontent.com/48608506/157249544-c412ac8e-71e2-4387-8037-b5129735e72e.png">
Hello! I just realised I receive this error halfway through. Have I done something wrong?

**Comment by josephmachado** [comment] 2022-03-09 13:35
@shivnarayanan Could you please check if your docker setting has at least 4GB memory ?

**Comment by kokoWoo** [comment] 2022-04-05 06:29
You need to check airflow-webserve1 of docker container and airflow-webserver1 of setup_infra.sh. setup_infra.sh written beginner_de_project_airflow_webserver_1.

**Comment by VentureFurther** [comment] 2022-04-21 04:22
> <img alt="image" width="567" src="https://user-images.githubusercontent.com/48608506/157168000-0541c9f2-bcfc-4c60-a4b4-855dda05aad8.png">

@shivnarayanan 
The container name is incorrect in the old script `setup_infra.sh`
It should be `beginner_de_project-airflow-webserver-1`, but the one in the script is `beginner_de_project_airflow-webserver_1`. Difference being that "_" should be "-". I had the same errors and fixed it by doing this.

**Comment by josephmachado** [comment] 2022-04-21 09:52
@shivnarayanan I put up a fix for this, can you pull master branch and try again?

**Closed** 2022-05-05 20:39 UTC
